// data.js

export const FACTIONS = [
    // Base Game
    { name: "The Arborec", expansion: "Base", complexity: 3 },
    { name: "The Barony of Letnev", expansion: "Base", complexity: 1 },
    { name: "The Clan of Saar", expansion: "Base", complexity: 2 },
    { name: "The Embers of Muaat", expansion: "Base", complexity: 3 },
    { name: "The Emirates of Hacan", expansion: "Base", complexity: 1 },
    { name: "The Federation of Sol", expansion: "Base", complexity: 1 },
    { name: "The Ghosts of Creuss", expansion: "Base", complexity: 2 },
    { name: "The L1Z1X Mindnet", expansion: "Base", complexity: 1 },
    { name: "The Mentak Coalition", expansion: "Base", complexity: 2 },
    { name: "The Naalu Collective", expansion: "Base", complexity: 2 },
    { name: "The Nekro Virus", expansion: "Base", complexity: 3 },
    { name: "The Sardakk N'orr", expansion: "Base", complexity: 2 },
    { name: "The Universities of Jol-Nar", expansion: "Base", complexity: 1 },
    { name: "The Winnu", expansion: "Base", complexity: 2 },
    { name: "The Xxcha Kingdom", expansion: "Base", complexity: 1 },
    { name: "The Yin Brotherhood", expansion: "Base", complexity: 2 },
    { name: "The Yssaril Tribes", expansion: "Base", complexity: 2 },
    // Prophecy of Kings
    { name: "The Argent Flight", expansion: "PoK", complexity: 1 },
    { name: "The Empyrean", expansion: "PoK", complexity: 2 },
    { name: "The Mahact Gene-Sorcerers", expansion: "PoK", complexity: 3 },
    { name: "The Naaz-Rokha Alliance", expansion: "PoK", complexity: 2 },
    { name: "The Titans of Ul", expansion: "PoK", complexity: 1 },
    { name: "The Vuil'Raith Cabal", expansion: "PoK", complexity: 3 },
    // Discordant Stars
    { name: "The Augurs of Ilyx", expansion: "Discordant", complexity: 3 },
    { name: "The Bentor Conglomerate", expansion: "Discordant", complexity: 1 },
    { name: "The Berserkers of Kjalengard", expansion: "Discordant", complexity: 3 },
    { name: "The Celdauri Trade Federation", expansion: "Discordant", complexity: 2 },
    { name: "The Cheiran Hordes", expansion: "Discordant", complexity: 1 },
    { name: "The Dih-Mohn Flotilla", expansion: "Discordant", complexity: 2 },
    { name: "The Edyn Mandate", expansion: "Discordant", complexity: 2 },
    { name: "The Florzen Profiteers", expansion: "Discordant", complexity: 2 },
    { name: "The Free Systems Compact", expansion: "Discordant", complexity: 2 },
    { name: "The Ghemina Raiders", expansion: "Discordant", complexity: 1 },
    { name: "The Ghoti Wayfarers", expansion: "Discordant", complexity: 2 },
    { name: "The Gledge Union", expansion: "Discordant", complexity: 2 },
    { name: "The Glimmer of Mortheus", expansion: "Discordant", complexity: 3 },
    { name: "The Kollecc Society", expansion: "Discordant", complexity: 3 },
    { name: "The Kortali Tribunal", expansion: "Discordant", complexity: 1 },
    { name: "The Kyro Sodality", expansion: "Discordant", complexity: 1 },
    { name: "The L'tokk Khrask", expansion: "Discordant", complexity: 2 },
    { name: "The Lanefir Remnants", expansion: "Discordant", complexity: 1 },
    { name: "The Li-Zho Dynasty", expansion: "Discordant", complexity: 3 },
    { name: "The Mirveda Protectorate", expansion: "Discordant", complexity: 2 },
    { name: "The Monks of Kolume", expansion: "Discordant", complexity: 3 },
    { name: "The Myko-Mentori", expansion: "Discordant", complexity: 1 },
    { name: "The Nivyn Star Kings", expansion: "Discordant", complexity: 2 },
    { name: "The Nokar Sellships", expansion: "Discordant", complexity: 2 },
    { name: "The Olradin League", expansion: "Discordant", complexity: 3 },
    { name: "The Roh'Dhna Mechatronics", expansion: "Discordant", complexity: 1 },
    { name: "The Savages of Cymiae", expansion: "Discordant", complexity: 2 },
    { name: "The Shipwrights of Axis", expansion: "Discordant", complexity: 2 },
    { name: "The Tnelis Syndicate", expansion: "Discordant", complexity: 2 },
    { name: "The Vaden Banking Clans", expansion: "Discordant", complexity: 1 },
    { name: "The Vaylerian Scourge", expansion: "Discordant", complexity: 2 },
    { name: "The Veldyr Sovereignty", expansion: "Discordant", complexity: 1 },
    { name: "The Zealots of Rhodun", expansion: "Discordant", complexity: 3 },
    { name: "The Zelian Purifier", expansion: "Discordant", complexity: 2 },
    // Thunder's Edge
    { name: "The Crimson Rebellion", expansion: "Thunder's Edge", complexity: 2 },
    { name: "The Deepwrought Scholarate", expansion: "Thunder's Edge", complexity: 2 },
    { name: "The Firmament / The Obsidian", expansion: "Thunder's Edge", complexity: 3 },
    { name: "Last Bastion", expansion: "Thunder's Edge", complexity: 2 },
    { name: "The Ral Nel Consortium", expansion: "Thunder's Edge", complexity: 2 },
];

export const SYSTEMS = [
    { id: 19, name: "Arnor/Lor", planets: [{ res: 2, inf: 1 }, { res: 1, inf: 2 }] },
    { id: 20, name: "Arinam/Meer", planets: [{ res: 1, inf: 2, trait: "industrial" }, { res: 0, inf: 4, trait: "hazardous" }] },
    { id: 21, name: "Abyz/Fria", planets: [{ res: 3, inf: 0, trait: "hazardous" }, { res: 2, inf: 0, trait: "hazardous" }] },
    { id: 22, name: "Corneeq/Resculon", planets: [{ res: 1, inf: 2 }, { res: 2, inf: 0 }] },
    { id: 23, name: "Centauri/Gral", planets: [{ res: 1, inf: 3, trait: "cultural" }, { res: 1, inf: 1, tech: "propulsion", trait: "industrial" }] },
    { id: 24, name: "Dal Bootha/Xxehan", planets: [{ res: 0, inf: 2, trait: "cultural" }, { res: 1, inf: 1 }] },
    { id: 25, name: "Bereg/Lirta IV", planets: [{ res: 3, inf: 1, trait: "hazardous" }, { res: 2, inf: 3, trait: "hazardous" }] },
    { id: 26, name: "Lazar/Sakulag", planets: [{ res: 1, inf: 2, tech: "cybernetic" }, { res: 2, inf: 1 }] },
    { id: 27, name: "Saudor", planets: [{ res: 2, inf: 2 }] },
    { id: 28, name: "Mehar Xull", planets: [{ res: 1, inf: 3, tech: "warfare", trait: "hazardous" }] },
    { id: 29, name: "Quann", planets: [{ res: 2, inf: 1, trait: "cultural" }] },
    { id: 30, name: "Lodor", planets: [{ res: 3, inf: 1, trait: "cultural" }] },
    { id: 31, name: "New Albion/Starpoint", planets: [{ res: 3, inf: 1, tech: "propulsion" }, { res: 1, inf: 0 }] },
    { id: 32, name: "Tequ'ran/Torkan", planets: [{ res: 2, inf: 0 }, { res: 0, inf: 3, trait: "cultural" }] },
    { id: 33, name: "Qucen'n/Rarron", planets: [{ res: 1, inf: 2 }, { res: 0, inf: 3, trait: "cultural" }] },
    { id: 34, name: "Mellon/Zohbat", planets: [{ res: 0, inf: 2, trait: "cultural" }, { res: 3, inf: 1, trait: "hazardous" }] },
    { id: 35, name: "Vefut II", planets: [{ res: 2, inf: 2, tech: "warfare" }] },
    { id: 36, name: "Thibah", planets: [{ res: 1, inf: 1, tech: "propulsion", trait: "industrial" }] },
    { id: 37, name: "Wellon", planets: [{ res: 1, inf: 2, tech: "cybernetic", trait: "industrial" }] },
    { id: 38, name: "Tar'mann", planets: [{ res: 1, inf: 1, tech: "biotic", trait: "industrial" }] },
    { id: 39, name: "Nestphar", wormhole: "alpha", planets: [{ res: 3, inf: 2 }] },
    { id: 40, name: "Loki/Abaddon/Moll Primus", wormhole: "beta", planets: [{ res: 1, inf: 2 }, { res: 1, inf: 0 }, { res: 4, inf: 1, legendary: true }] },
    { id: 69, name: "Archon Ren/Archon Tau", planets: [{ res: 2, inf: 3 }, { res: 1, inf: 1 }] },
    { id: 70, name: "Perimeter", planets: [{ res: 2, inf: 1 }] },
    { id: 71, name: "Ang", planets: [{ res: 2, inf: 0, tech: "warfare" }] },
    { id: 72, name: "Sem-Lore", planets: [{ res: 3, inf: 2, tech: "cybernetic", legendary: true }] },
    { id: 73, name: "Vorhal", planets: [{ res: 0, inf: 2, tech: "biotic" }] },
    { id: 74, name: "Atlas", wormhole: "beta", planets: [{ res: 3, inf: 1 }] },
    { id: 75, name: "Cealdri", wormhole: "gamma", planets: [{ res: 2, inf: 3, tech: "propulsion" }] },
    { id: 76, name: "The Dark", planets: [{ res: 3, inf: 4 }] },
    { id: 77, name: "Xanhact", planets: [{ res: 0, inf: 1 }] },
    { id: 78, name: "Vega Major/Vega Minor", planets: [{ res: 2, inf: 1 }, { res: 1, inf: 2, tech: "warfare" }] },
    { id: 79, name: "Hope's End", planets: [{ res: 3, inf: 0, legendary: true, trait: "hazardous" }] },
    { id: 80, name: "Rigel I/Rigel II/Rigel III", planets: [{ res: 0, inf: 1 }, { res: 1, inf: 2 }, { res: 1, inf: 0, tech: "cybernetic" }] }
];

export const ANOMALIES = [
    { name: "Asteroid Field", type: "anomaly" },
    { name: "Asteroid Field", type: "anomaly" },
    { name: "Asteroid Field", type: "anomaly" },
    { name: "Asteroid Field", type: "anomaly" },
    { name: "Nebula", type: "anomaly" },
    { name: "Nebula", type: "anomaly" },
    { name: "Nebula", type: "anomaly" },
    { name: "Supernova", type: "anomaly" },
    { name: "Supernova", type: "anomaly" },
    { name: "Gravity Rift", type: "anomaly", wormhole: "nexus" },
    { name: "Gravity Rift", type: "anomaly", wormhole: "nexus" },
    { name: "Empty Space", type: "empty" },
    { name: "Empty Space", type: "empty" },
    { name: "Empty Space", type: "empty" },
    { name: "Empty Space", type: "empty" },
    { name: "Empty Space", type: "empty" }
];